# fly.toml app configuration file generated for cold-bush-7260 on 2023-06-05T23:08:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-bush-7260"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
